name: 功能建议
description: 描述需要解决的具体场景
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 使用场景和问题
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 希望的行为
    validations:
      required: true
